configs:
- id: alphaMaintenanceWindow
  config:
    name: "auto.Alpha"
    template: object.json
    skip: false
    parameters:
      mz_id:
        configId: alphaManagmentZone
        configType: builtin:management-zones
        property: id
        type: reference
  type:
    settings:
      schema: builtin:alerting.maintenance-window
      schemaVersion: 2.14.4
      scope: environment
- id: bravoMaintenanceWindow
  config:
    name: auto.Bravo"
    template: object.json
    skip: false
    parameters:
      mz_id:
        configId: bravoManagmentZone
        configType: builtin:management-zones
        property: id
        type: reference
  type:
    settings:
      schema: builtin:alerting.maintenance-window
      schemaVersion: 2.14.4
      scope: environment
