apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    team: bravo
    dt.owner: bravo
  annotations:
    team: bravo
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        app.kubernetes.io/name: mongodb
        app.kubernetes.io/part-of: easytravel
        team: bravo
        dt.owner: bravo
        app.kubernetes.io/version: v1
      annotations:
        team: bravo
        dt.owner: bravo
        stage: v1
        product: mongodb
    spec:
      containers:
        - image: dynatrace/easytravel-mongodb
          name: mongodb
          env:
            - name: DT_RELEASE_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/version']
            - name: DT_RELEASE_PRODUCT
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/part-of']
            - name: DT_RELEASE_BUILD_VERSION
              value: 1.0.1
            - name: DT_RELEASE_STAGE
              value: v1
            - name: MY_PG_NAME
              value: easytravel-mongodb
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
              protocol: TCP
            - containerPort: 28017
              protocol: TCP
          resources:
            requests:
              memory: "100Mi"
            limits:
              memory: "100Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/part-of: easytravel
    team: bravo
    dt.owner: bravo
    app.kubernetes.io/version: 1.0.1
spec:
  ports:
    - name: "27017"
      port: 27017
      protocol: TCP
      targetPort: 27017
    - name: "28017"
      port: 28017
      protocol: TCP
      targetPort: 28017
  selector:
    app: mongodb
  type: ClusterIP
