apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    team: alpha
    dt.owner: alpha
  annotations:
    team: alpha
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        team: alpha
        dt.owner: alpha
        app.kubernetes.io/name: nginx
        app.kubernetes.io/version: v1
        app.kubernetes.io/part-of: easytravel
      annotations:
        team: alpha
        dt.owner: alpha
        stage: v1
        product: nginx
    spec:
      containers:
        - env:
            - name: ET_ANGULAR_FRONTEND_LOCATION
              value: angular-frontend-service-v1:8080
            - name: ET_BACKEND_LOCATION
              value: backend-service:8080
            - name: DT_RELEASE_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/version']
            - name: DT_RELEASE_PRODUCT
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/part-of']
            - name: DT_RELEASE_BUILD_VERSION
              value: 1.0.1
            - name: DT_RELEASE_STAGE
              value: v1
            - name: MY_PG_NAME
              value: easytravel-nginx
          image: dynatrace/easytravel-nginx
          imagePullPolicy: Always
          name: nginx
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 9079
              protocol: TCP
          resources:
            requests:
              memory: "150Mi"
            limits:
              memory: "150Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: angular-nginx-service
  labels:
    team: alpha
    dt.owner: alpha
    app.kubernetes.io/version: 1.0.1
    app.kubernetes.io/name: nginx
    app.kubernetes.io/part-of: easytravel
spec:
  ports:
    - protocol: TCP
      targetPort: 9079
      port: 80
  selector:
    app: nginx
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  defaultBackend:
    service:
      name: angular-nginx-service
      port:
        number: 80

